[package]
name = "luar-parser"
description = "Parser producing the LuaR syntax tree."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
luar-diagnostics = { workspace = true }
luar-ast = { workspace = true }
luar-lexer = { workspace = true }

[lints]
workspace = true
