[package]
name = "luar-driver"
description = "Compilation pipeline driver for LuaR."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
luar-diagnostics = { workspace = true }
luar-ast = { workspace = true }
luar-lexer = { workspace = true }
luar-parser = { workspace = true }
luar-sema = { workspace = true }
luar-lir = { workspace = true }
luar-codegen = { workspace = true }

[lints]
workspace = true
