[package]
name = "luar-codegen"
description = "Machine code emission for LuaR."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
luar-diagnostics = { workspace = true }
luar-lir = { workspace = true }

cranelift-codegen = { workspace = true }
cranelift-native = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-module = { workspace = true }
cranelift-object = { workspace = true }
target-lexicon = { workspace = true }
wasm-encoder = { workspace = true }

[target.'cfg(windows)'.dependencies]
cc = { workspace = true }

[lints]
workspace = true
